### ISSUE TITLE
bug: standalone "migrate" doesn't seem to enable maintenance mode

### ISSUE THREAD

**Issue by ankush** [frappe/agent#37]
<img width="1139" alt="Screenshot 2022-09-08 at 7 32 58 PM" src="https://user-images.githubusercontent.com/9079960/189146133-0ac46b3d-9833-4738-8484-1a6306c2cd81.png">

Based on this code, it seems it directly issues `migrate`. I am not entirely sure if this is handled somewhere else. 

https://github.com/frappe/agent/blob/6ea14dd82af277300887986535ac71b44c87cc55/agent/site.py#L374-L379

This was fine before because patch and doctype schemas had their own ad-hoc maintenance mode that blocked writes. But that's going away now with https://github.com/frappe/frappe/pull/18050/commits/8c7d6ab312b358ca6ef33844090893f1b0ad8986

Additionally, that ad-hoc maintenance mode only covers doctype schema and patches. So this bug needs to be fixed regardless of the linked PR.

**Comment by ankush** [comment]
@adityahase

**Comment by ankush** [comment]
@shadrak98 this is fairly simple to fix. Enable maintenance mode before, disable it after.

**Comment by shadrak98** [comment]
Seems to be fixed by https://github.com/frappe/press/commit/734a0763e4751de8988825f7b74bc765de70284d
